

import requests
from typing import Dict, Optional

# Database dinh dưỡng cơ bản 
NUTRITION_DATABASE = {
    # TRÁI CÂY VÀ RAU CỦ (trên 100g)
    'apple': {
        'calories': 52,
        'protein': 0.3,
        'carbs': 14,
        'fat': 0.2,
        'fiber': 2.4,
        'vitamin_c': 4.6,
        'benefits': ['Giàu chất xơ', 'Tốt cho tim mạch', 'Chứa nhiều chất chống oxi hóa'],
    },
    'banana': {
        'calories': 89,
        'protein': 1.1,
        'carbs': 23,
        'fat': 0.3,
        'fiber': 2.6,
        'potassium': 358,
        'benefits': ['Giàu kali', 'Tăng năng lượng', 'Tốt cho tiêu hóa'],
    },
    'beetroot': {
        'calories': 43,
        'protein': 1.6,
        'carbs': 10,
        'fat': 0.2,
        'fiber': 2.8,
        'benefits': ['Tăng sức bền', 'Tốt cho gan', 'Giàu chất chống oxi hóa'],
    },
    'bell pepper': {
        'calories': 31,
        'protein': 1,
        'carbs': 6,
        'fat': 0.3,
        'fiber': 2.1,
        'benefits': ['Giàu vitamin C', 'Màu sắc đẹp', 'Chống oxi hóa'],
    },
    'cabbage': {
        'calories': 25,
        'protein': 1.3,
        'carbs': 6,
        'fat': 0.1,
        'fiber': 2.5,
        'benefits': ['Tốt cho tiêu hóa', 'Chống ung thư', 'Giàu vitamin C'],
    },
    'capsicum': {
        'calories': 31,
        'protein': 1,
        'carbs': 6,
        'fat': 0.3,
        'fiber': 2.1,
        'benefits': ['Giàu vitamin C', 'Chống oxi hóa', 'Tốt cho mắt'],
    },
    'carrot': {
        'calories': 41,
        'protein': 0.9,
        'carbs': 10,
        'fat': 0.2,
        'fiber': 2.8,
        'vitamin_a': 835,
        'benefits': ['Tốt cho mắt', 'Giàu beta-carotene', 'Tăng cường miễn dịch'],
    },
    'cauliflower': {
        'calories': 25,
        'protein': 1.9,
        'carbs': 5,
        'fat': 0.3,
        'fiber': 2,
        'benefits': ['Ít calo', 'Giàu vitamin C', 'Chống viêm'],
    },
    'chilli pepper': {
        'calories': 40,
        'protein': 1.9,
        'carbs': 9,
        'fat': 0.4,
        'fiber': 1.5,
        'benefits': ['Tăng chuyển hóa', 'Giảm đau', 'Chống viêm'],
    },
    'corn': {
        'calories': 86,
        'protein': 3.3,
        'carbs': 19,
        'fat': 1.4,
        'fiber': 2.7,
        'benefits': ['Giàu năng lượng', 'Chứa chất xơ', 'Tốt cho tiêu hóa'],
    },
    'cucumber': {
        'calories': 15,
        'protein': 0.7,
        'carbs': 3.6,
        'fat': 0.1,
        'fiber': 0.5,
        'vitamin_k': 16.4,
        'benefits': ['Giàu nước', 'Giúp giải nhiệt', 'Tốt cho da'],
    },
    'eggplant': {
        'calories': 25,
        'protein': 1,
        'carbs': 6,
        'fat': 0.2,
        'fiber': 3,
        'benefits': ['Ít calo', 'Giàu chất xơ', 'Chống oxi hóa'],
    },
    'garlic': {
        'calories': 149,
        'protein': 6.4,
        'carbs': 33,
        'fat': 0.5,
        'fiber': 2.1,
        'benefits': ['Kháng sinh tự nhiên', 'Tăng miễn dịch', 'Giảm huyết áp'],
    },
    'ginger': {
        'calories': 80,
        'protein': 1.8,
        'carbs': 18,
        'fat': 0.8,
        'fiber': 2,
        'benefits': ['Chống buồn nôn', 'Chống viêm', 'Tốt cho tiêu hóa'],
    },
    'grapes': {
        'calories': 69,
        'protein': 0.7,
        'carbs': 18,
        'fat': 0.2,
        'fiber': 0.9,
        'benefits': ['Chống oxi hóa', 'Tốt cho tim', 'Chống lão hóa'],
    },
    'jalepeno': {
        'calories': 29,
        'protein': 0.9,
        'carbs': 6,
        'fat': 0.4,
        'fiber': 2.8,
        'benefits': ['Tăng trao đổi chất', 'Giàu vitamin C', 'Chống viêm'],
    },
    'kiwi': {
        'calories': 61,
        'protein': 1.1,
        'carbs': 15,
        'fat': 0.5,
        'fiber': 3,
        'vitamin_c': 93,
        'benefits': ['Rất giàu vitamin C', 'Hỗ trợ miễn dịch', 'Tốt cho tiêu hóa'],
    },
    'lemon': {
        'calories': 29,
        'protein': 1.1,
        'carbs': 9,
        'fat': 0.3,
        'fiber': 2.8,
        'vitamin_c': 53,
        'benefits': ['Giàu vitamin C', 'Giải độc', 'Tăng cường miễn dịch'],
    },
    'lettuce': {
        'calories': 15,
        'protein': 1.4,
        'carbs': 2.9,
        'fat': 0.2,
        'fiber': 1.3,
        'vitamin_k': 126,
        'benefits': ['Ít calo', 'Giàu vitamin K', 'Tốt cho xương'],
    },
    'mango': {
        'calories': 60,
        'protein': 0.8,
        'carbs': 15,
        'fat': 0.4,
        'fiber': 1.6,
        'vitamin_c': 36.4,
        'benefits': ['Giàu vitamin A', 'Tốt cho da', 'Tăng miễn dịch'],
    },
    'onion': {
        'calories': 40,
        'protein': 1.1,
        'carbs': 9,
        'fat': 0.1,
        'fiber': 1.7,
        'benefits': ['Kháng khuẩn', 'Tốt cho tim', 'Chống viêm'],
    },
    'orange': {
        'calories': 47,
        'protein': 0.9,
        'carbs': 12,
        'fat': 0.1,
        'fiber': 2.4,
        'vitamin_c': 53.2,
        'benefits': ['Giàu vitamin C', 'Tăng cường miễn dịch', 'Chống cảm cúm'],
    },
    'paprika': {
        'calories': 282,
        'protein': 14.1,
        'carbs': 54,
        'fat': 13,
        'fiber': 34.9,
        'benefits': ['Giàu chất chống oxi hóa', 'Tăng hương vị', 'Chống viêm'],
    },
    'pear': {
        'calories': 57,
        'protein': 0.4,
        'carbs': 15,
        'fat': 0.1,
        'fiber': 3.1,
        'benefits': ['Giàu chất xơ', 'Tốt cho tim', 'Ít calo'],
    },
    'peas': {
        'calories': 81,
        'protein': 5.4,
        'carbs': 14,
        'fat': 0.4,
        'fiber': 5.7,
        'benefits': ['Giàu protein thực vật', 'Nhiều chất xơ', 'Tốt cho tiêu hóa'],
    },
    'pineapple': {
        'calories': 50,
        'protein': 0.5,
        'carbs': 13,
        'fat': 0.1,
        'fiber': 1.4,
        'benefits': ['Giàu enzyme', 'Hỗ trợ tiêu hóa', 'Chống viêm'],
    },
    'pomegranate': {
        'calories': 83,
        'protein': 1.7,
        'carbs': 19,
        'fat': 1.2,
        'fiber': 4,
        'benefits': ['Chống oxi hóa mạnh', 'Tốt cho tim', 'Chống viêm'],
    },
    'potato': {
        'calories': 77,
        'protein': 2,
        'carbs': 17,
        'fat': 0.1,
        'fiber': 2.1,
        'potassium': 425,
        'benefits': ['Giàu năng lượng', 'Chứa nhiều kali', 'Tốt cho tiêu hóa'],
    },
    'raddish': {
        'calories': 16,
        'protein': 0.7,
        'carbs': 3.4,
        'fat': 0.1,
        'fiber': 1.6,
        'benefits': ['Ít calo', 'Giàu vitamin C', 'Hỗ trợ tiêu hóa'],
    },
    'soy beans': {
        'calories': 147,
        'protein': 12.9,
        'carbs': 11,
        'fat': 6.8,
        'fiber': 4.2,
        'benefits': ['Giàu protein thực vật', 'Tốt cho tim', 'Chứa isoflavone'],
    },
    'spinach': {
        'calories': 23,
        'protein': 2.9,
        'carbs': 3.6,
        'fat': 0.4,
        'fiber': 2.2,
        'benefits': ['Giàu sắt', 'Tốt cho máu', 'Nhiều vitamin K'],
    },
    'sweetcorn': {
        'calories': 86,
        'protein': 3.3,
        'carbs': 19,
        'fat': 1.4,
        'fiber': 2.7,
        'benefits': ['Giàu năng lượng', 'Ngọt tự nhiên', 'Chứa lutein'],
    },
    'sweetpotato': {
        'calories': 86,
        'protein': 1.6,
        'carbs': 20,
        'fat': 0.1,
        'fiber': 3,
        'vitamin_a': 709,
        'benefits': ['Giàu beta-carotene', 'Chỉ số đường huyết thấp', 'Tốt cho mắt'],
    },
    'tomato': {
        'calories': 18,
        'protein': 0.9,
        'carbs': 3.9,
        'fat': 0.2,
        'fiber': 1.2,
        'vitamin_c': 13.7,
        'benefits': ['Giàu lycopene', 'Chống ung thư', 'Tốt cho da'],
    },
    'turnip': {
        'calories': 28,
        'protein': 0.9,
        'carbs': 6,
        'fat': 0.1,
        'fiber': 1.8,
        'benefits': ['Ít calo', 'Giàu vitamin C', 'Tốt cho xương'],
    },
    'watermelon': {
        'calories': 30,
        'protein': 0.6,
        'carbs': 8,
        'fat': 0.2,
        'fiber': 0.4,
        'benefits': ['Giàu nước', 'Giải nhiệt', 'Ít calo'],
    },
    
    # Món ăn Việt Nam (mỗi khẩu phần ~300-400g)
    'Pho': {
        'calories': 350,
        'protein': 15,
        'carbs': 50,
        'fat': 8,
        'fiber': 3,
        'sodium': 1200,
        'benefits': ['Đầy đủ dinh dưỡng', 'Giàu protein', 'Nước dùng bổ dưỡng'],
    },
    'Banh mi': {
        'calories': 400,
        'protein': 18,
        'carbs': 45,
        'fat': 15,
        'fiber': 2,
        'sodium': 800,
        'benefits': ['Tiện lợi', 'Đa dạng dinh dưỡng', 'Ngon miệng'],
    },
    'Com tam': {
        'calories': 450,
        'protein': 20,
        'carbs': 60,
        'fat': 12,
        'fiber': 2,
        'sodium': 900,
        'benefits': ['Nhiều năng lượng', 'Giàu protein', 'Đầy bụng'],
    },
    'Bun bo Hue': {
        'calories': 420,
        'protein': 22,
        'carbs': 48,
        'fat': 14,
        'fiber': 3,
        'sodium': 1500,
        'benefits': ['Cay nóng', 'Giàu protein', 'Kích thích tiêu hóa'],
    },
    'Goi cuon': {
        'calories': 150,
        'protein': 8,
        'carbs': 20,
        'fat': 4,
        'fiber': 2,
        'sodium': 400,
        'benefits': ['Ít calo', 'Tươi mát', 'Nhiều rau sống'],
    },
    'Banh xeo': {
        'calories': 320,
        'protein': 12,
        'carbs': 35,
        'fat': 14,
        'fiber': 2,
        'sodium': 700,
        'benefits': ['Giòn ngon', 'Nhiều rau', 'Protein từ tôm thịt'],
    },
    'Banh cuon': {
        'calories': 200,
        'protein': 10,
        'carbs': 30,
        'fat': 5,
        'fiber': 1,
        'sodium': 600,
        'benefits': ['Nhẹ nhàng', 'Dễ tiêu hóa', 'Ít dầu mỡ'],
    },
    'Hu tieu': {
        'calories': 380,
        'protein': 16,
        'carbs': 52,
        'fat': 10,
        'fiber': 2,
        'sodium': 1100,
        'benefits': ['Nước dùng ngọt', 'Đa dạng topping', 'Đầy đủ dinh dưỡng'],
    },
    'Cao lau': {
        'calories': 400,
        'protein': 18,
        'carbs': 55,
        'fat': 12,
        'fiber': 3,
        'sodium': 900,
        'benefits': ['Đặc sản Hội An', 'Độc đáo', 'Giàu hương vị'],
    },
    'Banh beo': {
        'calories': 180,
        'protein': 6,
        'carbs': 28,
        'fat': 5,
        'fiber': 1,
        'sodium': 500,
        'benefits': ['Nhẹ nhàng', 'Đặc sản Huế', 'Dễ ăn'],
    },
    'Banh bot loc': {
        'calories': 220,
        'protein': 8,
        'carbs': 32,
        'fat': 7,
        'fiber': 1.5,
        'sodium': 550,
        'benefits': ['Dai ngon', 'Giàu protein từ tôm', 'Đặc sản miền Trung'],
    },
    'Banh can': {
        'calories': 160,
        'protein': 7,
        'carbs': 22,
        'fat': 5,
        'fiber': 1,
        'sodium': 450,
        'benefits': ['Nhỏ gọn', 'Thơm ngon', 'Đặc sản miền Trung'],
    },
    'Banh canh': {
        'calories': 300,
        'protein': 14,
        'carbs': 42,
        'fat': 8,
        'fiber': 2,
        'sodium': 1000,
        'benefits': ['Sợi dai', 'Nước dùng đậm đà', 'Đầy bụng'],
    },
    'Banh chung': {
        'calories': 380,
        'protein': 12,
        'carbs': 65,
        'fat': 8,
        'fiber': 3,
        'sodium': 600,
        'benefits': ['Truyền thống Tết', 'Giàu năng lượng', 'Lâu no'],
    },
    'Banh duc': {
        'calories': 140,
        'protein': 5,
        'carbs': 25,
        'fat': 3,
        'fiber': 1,
        'sodium': 400,
        'benefits': ['Mát mẻ', 'Ít calo', 'Dễ tiêu'],
    },
    'Banh gio': {
        'calories': 250,
        'protein': 10,
        'carbs': 38,
        'fat': 7,
        'fiber': 2,
        'sodium': 650,
        'benefits': ['Tiện lợi', 'Đầy bụng', 'Thơm lá chuối'],
    },
    'Banh khot': {
        'calories': 280,
        'protein': 11,
        'carbs': 32,
        'fat': 12,
        'fiber': 1.5,
        'sodium': 600,
        'benefits': ['Giòn tan', 'Đặc sản Vũng Tàu', 'Nhiều topping'],
    },
    'Banh pia': {
        'calories': 320,
        'protein': 6,
        'carbs': 55,
        'fat': 10,
        'fiber': 2,
        'sodium': 200,
        'benefits': ['Ngọt ngào', 'Đặc sản Sóc Trăng', 'Lâu bảo quản'],
    },
    'Banh tet': {
        'calories': 360,
        'protein': 11,
        'carbs': 62,
        'fat': 7,
        'fiber': 3,
        'sodium': 550,
        'benefits': ['Truyền thống miền Nam', 'Giàu năng lượng', 'Nhân đậu ngon'],
    },
    'Banh trang nuong': {
        'calories': 200,
        'protein': 6,
        'carbs': 30,
        'fat': 6,
        'fiber': 1,
        'sodium': 500,
        'benefits': ['Giòn rụm', 'Ăn vặt', 'Đa dạng topping'],
    },
    'Bun dau mam tom': {
        'calories': 400,
        'protein': 18,
        'carbs': 45,
        'fat': 16,
        'fiber': 3,
        'sodium': 1200,
        'benefits': ['Đậm đà', 'Giàu protein', 'Độc đáo'],
    },
    'Bun mam': {
        'calories': 380,
        'protein': 20,
        'carbs': 44,
        'fat': 13,
        'fiber': 3,
        'sodium': 1400,
        'benefits': ['Đặc sản miền Tây', 'Nước dùng đậm đà', 'Nhiều hải sản'],
    },
    'Bun rieu': {
        'calories': 340,
        'protein': 16,
        'carbs': 46,
        'fat': 10,
        'fiber': 3,
        'sodium': 1100,
        'benefits': ['Giàu canxi', 'Nước dùng chua ngọt', 'Nhiều rau'],
    },
    'Bun thit nuong': {
        'calories': 420,
        'protein': 22,
        'carbs': 50,
        'fat': 14,
        'fiber': 3,
        'sodium': 900,
        'benefits': ['Thơm ngon', 'Giàu protein', 'Nhiều rau sống'],
    },
    'Ca kho to': {
        'calories': 280,
        'protein': 24,
        'carbs': 12,
        'fat': 15,
        'fiber': 1,
        'sodium': 1000,
        'benefits': ['Giàu omega-3', 'Đậm đà', 'Tốt cho tim mạch'],
    },
    'Canh chua': {
        'calories': 120,
        'protein': 10,
        'carbs': 15,
        'fat': 3,
        'fiber': 2,
        'sodium': 800,
        'benefits': ['Chua ngọt', 'Khai vị', 'Nhiều rau củ'],
    },
    'Chao long': {
        'calories': 220,
        'protein': 14,
        'carbs': 20,
        'fat': 9,
        'fiber': 1,
        'sodium': 900,
        'benefits': ['Bổ dưỡng', 'Ấm bụng', 'Giàu protein'],
    },
    'Mi quang': {
        'calories': 390,
        'protein': 18,
        'carbs': 52,
        'fat': 11,
        'fiber': 3,
        'sodium': 1000,
        'benefits': ['Đặc sản Quảng Nam', 'Đa dạng topping', 'Màu sắc bắt mắt'],
    },
    'Nem chua': {
        'calories': 180,
        'protein': 12,
        'carbs': 8,
        'fat': 11,
        'fiber': 0.5,
        'sodium': 700,
        'benefits': ['Chua ngọt', 'Lên men tự nhiên', 'Giàu probiotic'],
    },
    'Xoi xeo': {
        'calories': 350,
        'protein': 8,
        'carbs': 58,
        'fat': 10,
        'fiber': 2,
        'sodium': 400,
        'benefits': ['Giàu năng lượng', 'Thơm bùi', 'Ăn sáng lý tưởng'],
    },
}

def get_nutrition_info(food_name: str) -> Optional[Dict]:
    
    # Chuẩn hóa tên 
    food_name_normalized = food_name.strip()

    # Tìm trong database
    nutrition = NUTRITION_DATABASE.get(food_name_normalized)
    
    if nutrition:
        # Thêm tên vào kết quả
        result = {'name': food_name, **nutrition}
        return result
    
    # Nếu không tìm thấy, trả về thông tin mặc định
    return {
        'name': food_name,
        'calories': None,
        'protein': None,
        'carbs': None,
        'fat': None,
        'fiber': None,
        'benefits': ['Thông tin dinh dưỡng chưa có sẵn'],
        'note': 'Đang cập nhật dữ liệu'
    }


def get_nutrition_with_fallback(food_name: str, api_key: str = None, app_id: str = None) -> Dict:
    
    return get_nutrition_info(food_name)

def format_nutrition_display(nutrition: Dict) -> str:
    #Format thông tin dinh dưỡng thành chuỗi đẹp
    html = f"<h4> {nutrition['name']}</h4>"
    
    if nutrition.get('calories'):
        html += f"<p><strong>Calories:</strong> {nutrition['calories']} kcal</p>"
    
    if nutrition.get('protein'):
        html += f"<p><strong>Protein:</strong> {nutrition['protein']}g</p>"
    
    if nutrition.get('carbs'):
        html += f"<p><strong>Carbs:</strong> {nutrition['carbs']}g</p>"
    
    if nutrition.get('fat'):
        html += f"<p><strong>Fat:</strong> {nutrition['fat']}g</p>"
    
    if nutrition.get('benefits'):
        html += "<p><strong>Lợi ích:</strong></p><ul>"
        for benefit in nutrition['benefits']:
            html += f"<li>{benefit}</li>"
        html += "</ul>"
    
    return html